//
//  Coordenadas.swift
//  Aula 6
//
//  Created by Turma02-9 on 13/06/24.
//

import Foundation
import MapKit

struct Location: Identifiable
{
    let id = UUID()
    let name: String
    let coordinate: CLLocationCoordinate2D
    let flag: String
    let description: String
}

var arrayLocation = [
    Location(name: "Butão", 
             coordinate: CLLocationCoordinate2D(latitude: 27.5356304, longitude: 89.9421603),
             flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/250px-Flag_of_Bhutan.svg.png",
    description: "O Butão (em butanês: འབྲུག་ཡུལ་; romaniz.: Dru Ü, pronúncia: [ʈʂɦu yː], lit. Terra do Dragão), oficialmente Reino do Butão (འབྲུག་རྒྱལ་ཁབ་ Druk Gyal Khap),[4] é um país interior localizado no sul da Ásia, no extremo leste dos Himalaias. Faz fronteira a norte com a China e para o sul, leste e oeste pela Índia. Mais a oeste, está separado do Nepal pelo estado indiano de Siquim, enquanto mais ao sul está separado de Bangladesh pelos estados indianos de Assam e Bengala Ocidental. A capital e maior cidade do Butão é Thimbu. O Butão existia como uma manta de retalhos de pequenos feudos em guerra até o início do século XVII, quando o lama e líder militar Shabdrung Ngawang Namgyal, fugindo da perseguição religiosa no Tibete, unificou a área cultivada e uma identidade distinta butanesa. Mais tarde, no início do século XX, o Butão entrou em contato com o Império Britânico e manteve fortes relações bilaterais com a Índia sobre a sua independência. Em 2006, baseado em uma pesquisa global, a revista BusinessWeek avaliou o Butão o país mais feliz na Ásia e o oitavo país mais feliz do mundo. A paisagem do Butão varia de planícies subtropicais no sul às alturas sub-alpinas no norte dos Himalaias, onde alguns picos excedem a altitude de 7 000 metros. Em 1997 a área total foi relatada como cerca de 46 500 km² e de 38 394 km² em 2002. A religião oficial é o budismo vajrayana e é seguida pela grande maioria da população, estimada 802 163 em 2017. O hinduísmo é a segunda maior religião. Em 2008, o Butão fez a transição da monarquia absoluta para a monarquia constitucional e realizou a sua primeira eleição geral. Além de ser um membro da Organização das Nações Unidas, Butão é um membro da Associação Sul-Asiática para a Cooperação Regional (SAARC) e organizou em abril de 2010 o XVI congresso da SAARC.)"),
        Location(name: "Rick Roll Island",
                 coordinate: CLLocationCoordinate2D(latitude: 22.4438669, longitude: -74.22309),
                      flag: "https://www.giantfreakinrobot.com/wp-content/uploads/2022/08/rick-astley.jpg",
             description: "We're no strangers to love\nYou know the rules and so do I (do I)\nA full commitment's what I'm thinking of\nYou wouldn't get this from any other guy\nI just wanna tell you how I'm feeling\nGotta make you understand\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you\nWe've known each other for so long\nYour heart's been aching, but you're too shy to say it (say it)\nInside, we both know what's been going on (going on)\nWe know the game and we're gonna play it\nAnd if you ask me how I'm feeling\nDon't tell me you're too blind to see\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you\nWe've known each other for so long\nYour heart's been aching, but you're too shy to say it (to say it)\nInside, we both know what's been going on (going on)\nWe know the game and we're gonna play it\nI just wanna tell you how I'm feeling\nGotta make you understand\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you"),
    Location(name: "Atol de Bikini",
             coordinate: CLLocationCoordinate2D(latitude: 11.6143582, longitude: 165.2173801),
                  flag: "https://images.uncyc.org/pt/thumb/2/26/Fenda_do_Biqu%C3%ADni.jpg/600px-Fenda_do_Biqu%C3%ADni.jpg",
         description: "Atol de Bikini é um atol do Oceano Pacífico onde foram realizadas explosões atômicas experimentais, a primeira ocorrendo em julho de 1946. Também conhecido como Atol de Pikini, é um atol desabitado, devido à radioatividade resultante das explosões atômicas, de 6 km² localizado na Micronésia, Oceano Pacífico. O Atol de Bikini é membro das Ilhas Marshall e é formado por 36 ilhas que rodeiam uma lagoa. O local foi parte do programa de testes nucleares desenvolvido pelos Estados Unidos, após ser invadido durante a Segunda Guerra Mundial. No local foram lançadas mais de 20 bombas de hidrogênio e bombas nucleares, entre julho de 1946 e 1958.\nAntes da realização dos testes nucleares, a população nativa foi transferida para o Atol de Rongerik. No fim dos anos 1960 e começo dos anos 1970, alguns dos antigos moradores do Atol de Bikini retornaram das Ilhas Kili, mas foram novamente transferidos, devido a alta radioatividade.\nO navegador e explorador Otto von Kotzebue chamou o Atol Bikini como Atol Eschscholtz em homenagem ao cientista Johann Friedrich von Eschscholtz."),
    Location(name: "Seoul",
             coordinate: CLLocationCoordinate2D(latitude: 37.5676017, longitude: 126.9445991),
                  flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Seoul.svg/1920px-Flag_of_Seoul.svg.png",
         description: "Seul (em coreano: 서울, romanização revisada: Seoul, romanização McCune-Reischauer: Sŏul, pronunciado: [sʰʌ.ul], oficialmente Cidade Especial de Seul (coreano: 서울특별시; hanja: 서울特別市), é a capital e a maior metrópole da República da Coreia, mais conhecida como Coreia do Sul. A cidade é o núcleo da Região Metropolitana de Seul, que inclui a metrópole vizinha de Incheon e a província de Gyeonggi, a segunda maior área metropolitana do mundo, com mais de 25 milhões de habitantes.\nSituado às margens do rio Han, a história de Seul remonta a mais de dois mil anos, quando foi fundada em 18 a.C. por Baekje, um dos Três Reinos da Coreia. A cidade continuou como a capital coreana sob a Dinastia Joseon. A região de Seul contém cinco Patrimônios Mundiais da UNESCO: Complexo de Palácios de Ch'angdokkgung, Fortaleza de Hwasong, Santuário de Chongmyo, Namhansanseong e os Túmulos Reais da Dinastia Joseon. Seul é cercada por montanhas, sendo o monte Bukhan a mais alta delas, o parque nacional mais visitado do mundo por metro quadrado. Entre os marcos modernos estão a icônica N Seoul Tower, o dourado KLI 63 Building, o neofuturista Dongdaemun Plaza, o Lotte World, o segundo maior parque temático coberto do mundo, e a Ponte Banpo, a mais longa ponte-fonte do mundo. A capital sul-coreana foi eleita o destino turístico mais procurado do mundo por turistas chineses, japoneses e tailandeses por três anos consecutivos (2009-2011) e, com mais de 12 milhões de visitantes internacionais em 2013, é a 10ª cidade mais visitada do mundo.\nAtualmente, Seul é considerada uma cidade global importante, resultado do boom econômico chamado de Milagre do rio Han, que transformou-a de um amontoado de ruínas durante a Guerra da Coreia para a 4ª maior economia metropolitana do mundo, com um PIB de 774 bilhões de dólares em 2012, depois de Tóquio, Nova York e Los Angeles. A metrópole é a sede de empresas da Fortune Global 500, como a Samsung, a maior empresa de tecnologia do mundo, a LG e a Hyundai-Kia. Em 2013, o PIB (PPC) per capita da cidade de 39.448 dólares era comparável ao da França e Finlândia."),
    Location(name: "Monte Everest",
             coordinate: CLLocationCoordinate2D(latitude: 27.9920289, longitude: 86.8707941),
                  flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Flag_of_Nepal_%28white_background%2C_aspect_ratio_3-2%29.svg/1200px-Flag_of_Nepal_%28white_background%2C_aspect_ratio_3-2%29.svg.png",
         description: "O monte Everest ou, na sua forma portuguesa, Evereste, também conhecido no Nepal como Sagarmāthā (सगरमाथा), no Tibete como Chomolungma (ཇོ་མོ་གླང་མ) e Zhūmùlǎngmǎ Fēng em chinês (珠穆朗玛峰), é a montanha de maior altitude da Terra. Seu pico está a 8 848,86 metros acima do nível do mar, na subcordilheira Mahalangur Himal dos Himalaias. A fronteira internacional entre o distrito nepalês do Solukhumbu e o distrito de Tingri da Região Autônoma do Tibete da República Popular da China passa no cume. O maciço do Everest inclui diversos outros picos situados acima da zona da morte, incluindo os picos do Lhotse (8 516 m), Nuptse (7 855 m) e Changtse (7 580 m), entre outros.\nO Everest atrai muitos alpinistas, alguns deles experientes. Existem duas rotas principais de escalada: uma que se aproxima ao cume pela face sudeste, no Nepal (conhecida como a rota padrão) e outra pela face norte, no Tibete. Apesar da rota padrão não colocar desafios substanciais na técnica de escalada, o Everest apresenta perigos, tais como mal da montanha, condições climáticas, vento, bem como os perigos objetivos importantes, como avalanches. Em 2016, havia bem mais de 200 cadáveres na montanha, sendo que alguns deles chegam a servir como pontos de referência.\n"),
]
